version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: sql_osmarmy_com
      DB_PASS: 6858ce741b616
      DB_NAME: sql_osmarmy_com
      BASE_URL: http://localhost:3001
      ADMIN_PASSWORD: Ahfhfhfwjejbf
      SHORT_CODE_LENGTH: 6
    extra_hosts:
      - "host.docker.internal:host-gateway"
